config/routes.rb
Rails.application.routes.draw do
  root :to => 'session#new'
  #session routes

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :users
  resources :exercises, :except => [:new, :create, :index, :show]
  resources :workouts do
    resources :exercises, :only => [:new, :create]
  end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
    belongs_to :workout, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
    has_many :workouts
    has_many :exercises, :through => :workouts

    #create methods to calculate BMI and the category
    def self.bmi_calculator weight, height
        bmi = (weight/ height**2 * 10000).round(2)
    end

    def self.bmi_category bmi
        case
        when bmi < 18.5
            "Underweight"
        when bmi < 24.9 
            "Healthy Weight"
        when bmi < 29.9
            "Overweight"
        when bmi < 39.9
            "Severly Obese"
        else 
            "Morbidly Obese"
        end
    end

end

app/models/workout.rb
class Workout < ApplicationRecord
    belongs_to :user, :optional => true
    has_many :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user 

    private 
    def fetch_user 
        @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
        session[:user_id] = nil unless @current_user.present?
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end 

    def check_for_admin
        redirect_to root_path unless (@current_user.present? && @current_user.admin?)
    end

    def check_user
        redirect_to @current_user if @current_user.present?
    end

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
  end

  def new
    @exercise = Exercise.new
    @workout = Workout.find params[:workout_id]
  end

  def create 
    exercise = Exercise.create exercise_params
    workout = Workout.find params[:workout_id]
    workout.exercises << exercise
    redirect_to workout
  end 

  def show
  end

  def edit
    @exercise = Exercise.find params[:id]
  end

  def update
    exercise = Exercise.find params[:id]
    exercise.update exercise_params
    redirect_to workout_path(exercise.workout_id)
  end

  def destroy
    exercise = Exercise.find params[:id]
    exercise.destroy
    redirect_to workout_path(exercise.workout_id)

  end

  private

  def exercise_params
    params.require(:exercise).permit(:name, :weight, :repetitions, :sets, :distance, :duration)
  end 


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :check_user
    
    def home
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

    def new
    end

    def create
        user = User.find_by :email => params[:email]
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to user_path(session[:user_id])
        else 
            flash[:error] = "Email or password invalid. Please try again."
            redirect_to login_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]
  
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new 
    end

  end

  def show
    if @current_user.weight.present? && @current_user.height.present?
      @bmi = User.bmi_calculator(@current_user.weight, @current_user.height)
      @bmi_cat = User.bmi_category @bmi
    end
  end

  def edit
  end

  def update
    @current_user.update user_params
    redirect_to user_path(@current_user)
  end

  def destroy
    @current_user.destroy
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :height, :weight) #need to work out if I need to allow height and weight in here
  end
    
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :check_for_login
  
  def index
  end

  def new
    @workout = Workout.new
  end

  def create
    workout = Workout.create workout_params
    @current_user.workouts << workout
    redirect_to workout
  end

  def show
    @workout = Workout.find params[:id]
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Workout #{@workout.date}", template: "workouts/work.html.erb"  # Excluding ".pdf" extension.
      end
    end
  end

  def edit
    @workout = Workout.find params[:id]
  end

  def update
    workout = Workout.find params[:id]
    workout.update workout_params
    redirect_to workout
  end

  def destroy
    workout = Workout.find params[:id]
    workout.destroy
    redirect_to workouts_path
  end


  private 
  def workout_params
    params.require(:workout).permit(:date, :focus, :duration)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_form.html.erb
<%= form_for [@workout, @exercise]  do |f| %>
    
    <div class="row">
        <div class="col">
            <%= f.label :name, :class => 'form-label' %>
            <%= f.text_field :name, :required => true, :placeholder => "Create name or select existing exercise", :class => 'form-control mb-3' %>
        </div>
        <div class="col">
            <label> Select for an existing exercise</label>
            <%= select_tag "exercises", raw('<option></option><option>' + @current_user.exercises.pluck(:name).uniq.join('</option> <option>') + '</option>'), :class => 'form-select '%>
        </div>
    </div>

    <script>
    $('select').on('change', function(){
        const value = $(this).val()
        $('#exercise_name').val(value)
    })    
    </script>

    <%= f.label :weight, :class => 'form-label' %>
    <%= f.number_field :weight, :placeholder => "in kilograms", :class => 'form-control w-50 mb-3' %>

    <%= f.label :repetitions, :class => 'form-label' %>
    <%= f.number_field :repetitions, :class => 'form-control w-50' %>

    <%= f.label :sets, :class => 'form-label' %>
    <%= f.number_field :sets, :class => 'form-control w-50' %>

    <%= f.label :distance, :class => 'form-label' %>
    <%= f.number_field :distance, :placeholder => "in kilometers", :class => 'form-control w-50 mb-3' %>

    <%= f.label :duration, :class => 'form-label' %>
    <%= f.number_field :duration, :placeholder => "in minutes", :class => 'form-control w-50 mb-3' %>

    <%= f.submit "Create", :class => "btn btn-success mb-3 w-50" %>
<% end %>

app/views/exercises/edit.html.erb
<div class='pe-5 ps-5 view-window'>
  <h1>Edit Exercise</h1>
  <%= render :partial => "form" %>
</div>

app/views/exercises/new.html.erb
<div class='pe-5 ps-5 view-window'>
  <h1>Record Exercise</h1>
  <%= render :partial => 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GymTrackerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark mb-3 rounded-2 border border-light border-5">
        <div class="container-fluid text-light">
          <%= link_to "Home", root_path, :class => "nav-link" %>
          <% if @current_user.present? %>
            <%= link_to "Profile", user_path(@current_user), :class => "nav-link" %>
            <%= link_to "Workouts", workouts_path, :class => "nav-link" %>
            <%= link_to "Sign Out (#{ @current_user.email})", login_path, :method => 'delete', :class => "nav-link" %>
            <% if @current_user.admin%>
              <%= link_to 'All users', users_path, :class => "nav-link" %>
            <% end %>
          <% end %>
        </div>
    </nav>


    <div class='row'>
      <div class="home-page-image min-vh-100 col">
      
      </div>
      <div class='col d-flex align-items-center justify-content-center'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class='container-sm'>
    <h1>Log in</h1>
    <h5>Welcome back! Please enter your details.</h5>
    
            <%= link_to "Sign Up", new_user_path, :class => "btn btn-primary btn-lg"%>
            <%= button_to "Login", login_path, :method => "get", :class => "btn btn-secondary btn-lg"%>
    <% end %>
</div>

app/views/session/new.html.erb
<div class='pe-5 ps-5 view-window'>
    <%= image_tag("logo.png", :class => 'image-logo mx-auto d-block rounded-circle mb-3') %>
    <h3 class="text-center">Login</h1>
    <p class='fw-light text-center'>Welcome back! Please enter your details.</p>
    <%= form_tag login_path do %>
        <%= label_tag :email, nil ,:class => "form-label mb-1"%>
        <%= email_field_tag :email,nil, :class => "form-control w-100 mb-2" %>

        <%= label_tag :password, nil, :class => "form-label mb-1"%>
        <%= password_field_tag :password, nil, :class => "form-control w-100 mb-2" %>

        <%= submit_tag "Login", :class => "btn btn-dark mt-2 w-100" %>
    <% end %>
    <p class="text-muted text-center mt-1">
    Don't have an account? <%= link_to "Sign Up", new_user_path %> 
    </p>

    <% if flash[:error].present?%>
        <div class="alert alert-danger d-flex align-items-center p-1 center-text" role="alert">
            <%= flash[:error] %>
        </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<div class="container pe-5 ps-5 view-window">
    <h1>Edit Profile Info</h1>

    <%= form_for @current_user do |f| %>
        <%= f.label :name, :class => 'form-label' %>
        <%= f.text_field :name, :class => 'form-control w-50 mb-3' %>

        <%= f.label :height, :class => 'form-label' %>
        <%= f.number_field :height, :placeholder => "in cm", :class => 'form-control w-50 mb-3' %>

        <%= f.label :weight, :class => 'form-label' %>
        <%= f.number_field :weight, :placeholder => "in kgs", :class => 'form-control w-50 mb-3' %>

        <%= f.submit "Save Information", :class => "btn btn-success mt-2 w-50" %>
    <% end %>
</div>

app/views/users/index.html.erb
<div class='pe-5 ps-5 view-window'>
    <h1>All users</h1>

    <% @user.each do |user| %>
        <p>
            <%= "#{user.email} #{user.name}" %>
        </p>
    <% end %>
</div>

app/views/users/new.html.erb
<div class='pe-5 ps-5 view-window'>
    <%= image_tag("logo.png", :class => 'image-logo mx-auto d-block rounded-circle mb-3') %>
    <h3 class="text-center">Sign Up</h1>
    <%= form_for @user do |f| %>
        <%= f.label :email, :class => "form-label mb-1" %>
        <%= f.email_field :email, :class => "form-control w-100 mb-2" %>

        <%= f.label :password, :class => "form-label mb-1" %>
        <%= f.password_field :password, :class => "form-control w-100 mb-2" %>

        <%= f.label :password_confirmation, :class => "form-label mb-1" %>
        <%= f.password_field :password_confirmation, :class => "form-control w-100 mb-2" %>

        <%= f.submit "Register", :class => "btn btn-dark mt-2 w-100" %>
    <% end %>
    <p class="text-muted text-center mt-1">
    Return to <%= link_to "Login", root_path %>
    </p>
    <% if @user.errors.any? %>
        <ol>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ol>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="container pe-5 ps-5 view-window">
    <h1><%= @current_user.name %>'s Profile</h1>

    <p>Email: <%= @current_user.email %></p>

    <% if @current_user.name.present? %>
        <p>Name: <%= @current_user.name %></p>
        <% else %>
        <p>Update Profile to add name</p>   
    <% end %>

    <% if @current_user.height.present? %>
        <p>Height: <%= @current_user.height %>cm</p>
        <% else %>
        <p>Update Profile to add height</p>
    <% end %>

    <% if @current_user.weight.present? %>
        <p>Weight: <%= @current_user.weight %>kg</p>
        <% else %>
        <p>Update Profile to add weight</p> 
    <% end %>

    <% if  @current_user.weight.present? && @current_user.height.present? %>
        <p>BMI: <%= @bmi %> (<%= @bmi_cat %>)</p>
    <% end %>

    <div class="d-grid gap-2 d-md-flex justify-content-md-center">
        <%= button_to 'Update Profile', edit_user_path(@current_user), :method => "get", :class => "btn btn-primary btn-sm" %>
        <%= button_to 'View All Workouts', workouts_path, :method => 'get', :class => "btn btn-primary btn-sm" %>
        <%= button_to 'Delete Account' , user_path(@current_user), :method => "delete", :data => {:confirm => "Are you sure"}, :class => "btn btn-danger btn-sm"%>
    </div>
</div>

app/views/workouts/_form.html.erb
<%= form_for @workout do |f| %>
    <%= f.label :date, :class => 'form-label' %>
    <%= f.date_field :date, :class => 'form-control w-50 mb-3' %>

    <%= f.label :focus, :class => 'form-label' %>
    <%= f.text_field :focus, :class => 'form-control w-50 mb-3' %>

    <%= f.label :duration, :class => 'form-label' %>
    <%= f.number_field :duration, :placeholder => "In hours", :class => 'form-control w-50 mb-3' %>

    <%= f.submit :class => "btn btn-success mt-2 w-50" %>
<% end %>

app/views/workouts/edit.html.erb
<div class='container pe-1 ps-1 view-window'>
    <h1>Edit Workout</h1>
    <%= render :partial => 'form' %>
</div>

app/views/workouts/index.html.erb
<div class='mt-5'>
<div class="d-flex justify-content-between">
        <% if @current_user.name.present? %>
            <h1 class='mb-3'><%= @current_user.name %>'s Workouts</h1>
        <% else%>
            <h1>Your Workouts</h1>
        <% end %>
        <%= button_to "Add a workout", new_workout_path, :method => 'get', :class => "btn btn-primary flex-end" %>
    </div>
    <div class='container'>
        <% @current_user.workouts.order(:date).each_slice(2) do |row| %>
        <div class="row justify-content-between">
        <% row.each do |workout| %>
            <div class="card col-md-5 mb-3 border border-secondary">
                <div class="card-body">
                    <h5 class="card-title">Workout</h5>
                    <h6 class="card-subtitle mb-2 text-muted"><%= workout.date.strftime '%A %B %e, %Y' %></h6>
                    <p class="card-text">Includes <%= pluralize workout.exercises.count, 'exercise' %></p>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                        <%= button_to 'View details', workout_path(workout.id), :class => "card-link", :method => "get", :class => "btn btn-primary btn-sm" %>
                        <%= button_to 'Edit Workout Info', edit_workout_path(workout.id), :class => "card-link", :method => "get", :class => "btn btn-primary btn-sm" %>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
        <% end %>
    </div> 
</div>

app/views/workouts/new.html.erb
<div class='container pe-1 ps-1 view-window'>
    <h1>Record Workout</h1>
    <%= render :partial => 'form' %>
</div>

app/views/workouts/show.html.erb
<div class="container mt-5 pb-5 pe-5 ps-5">
    <div class="d-flex justify-content-between">
        <h1>Workout: <%= @workout.date.strftime '%a %b %e, %Y' %></h1>
        <%= link_to 'Add exercise', new_workout_exercise_path(@workout.id), :method => 'get', :class => "btn btn-primary btn-lg text-center" %>
    </div>
    <p>Duration of workout: <%= @workout.duration %></p>
    <p>Focus of Workout: <%= @workout.focus %></p>

    <% @workout.exercises.order(:created_at).each_slice(2).with_index do |row,i| %>
    <div class="row justify-content-evenly g-0">
    <% row.each_with_index do |exercise,index| %>
        <div class="card col-5 md-5 mb-3 border border-secondary">
            <div class="card-header">
                Exercise <%= 2*i + index + 1 %>: <%= exercise.name%>
            </div>
            <ul class="list-group list-group-flush">
            <% %i(weight sets repetitions distance duration).each do |method|%>
            <% if exercise.try(method)%>
                <li class="list-group-item"><%= method.to_s.capitalize %>: <%= exercise.try(method)%></li>
            <% end %>
        <% end %>
                <li class="list-group-item">
                    <div class="d-grid gap-2 d-md-flex justify-content-center">
                        <%= button_to 'Edit', edit_exercise_path(exercise.id), :method => 'get',:class => "btn btn-primary btn-sm" %>  
                        <%= button_to 'Delete', exercise_path(exercise.id), :method => "delete", :data => {:confirm => "Are you sure"},:class => "btn btn-danger btn-sm" %>
                    </div>
                </li>
            </ul>
        </div>
        <% end %>
    </div>
    <% end %>

    <div class="d-grid gap-2 d-md-flex justify-content-md-center">
        <%= button_to 'Back to Workouts', workouts_path, :method => "get", :class => "btn btn-primary btn-sm" %>
        <%= button_to 'Delete Workout' , @workout, :method => "delete", :data => {:confirm => "Are you sure"}, :class => "btn btn-danger btn-sm"%>
        <%= link_to 'Generate pdf', workout_path(@workout, :format => 'pdf'), :method => 'get', :target => '_blank', :class => "btn btn-primary btn-sm" %>
    </div>
</div>

app/views/workouts/work.html.erb
<h1>Workout: <%= @workout.date.strftime '%A %B %e, %Y' %></h1> 
<% @workout.exercises.each_with_index do |exercise, index|%>
    <h4>Exercise <%= index + 1 %>: <%= exercise.name %></h4>
    <ul>
    <% %i(weight repetitions sets distance duration).each do |method|%>
        <% if exercise.try(method)%>
            <li><%= method.to_s.capitalize %>: <%= exercise.try(method)%></li>
        <% end %>
    <% end %>
    </ul>
<% end %>
<hr>

app/views/workouts/workout.html.erb
<h1>Workout: <%= @workout.date.strftime '%A %B %e, %Y' %></h1> 


<% @workout.exercises.each_with_index do |exercise, index|%>
    <h4>Exercise <%= index + 1 %>: <%= exercise.name %></h4>
    <ul>
    <% %i(weight repetitions sets distance duration).each do |method|%>
        <% if exercise.try(method)%>
            <li><%= method.to_s.capitalize %>: <%= exercise.try(method)%></li>
        <% end %>
    <% end %>
    </ul>
<% end %>

<hr>